// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    Desktop: typeof import('./src/components/Header/Desktop/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    FooterList: typeof import('./src/components/Footer/List.vue')['default']
    FooterMenu: typeof import('./src/components/Footer/Menu.vue')['default']
    HeaderDesktop: typeof import('./src/components/Header/Desktop/index.vue')['default']
    List: typeof import('./src/components/Footer/List.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
