// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Container: typeof import('./src/components/Common/Container.vue')['default']
    Desktop: typeof import('./src/components/Header/Desktop/index.vue')['default']
    DownloadBanner: typeof import('./src/components/Landing/DownloadBanner.vue')['default']
    FAQ: typeof import('./src/components/FAQ/index.vue')['default']
    Features: typeof import('./src/components/Landing/Features/index.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Heading: typeof import('./src/components/Legal/Heading.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Legal: typeof import('./src/components/Legal/index.vue')['default']
    List: typeof import('./src/components/Footer/List.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MainScreen: typeof import('./src/components/Landing/MainScreen.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MobileAppBanner: typeof import('./src/components/Landing/MobileAppBanner.vue')['default']
    Opportunities: typeof import('./src/components/Landing/Opportunities.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondScreen: typeof import('./src/components/Landing/SecondScreen.vue')['default']
    Statistic: typeof import('./src/components/Landing/Statistic.vue')['default']
  }
}
