<template>
  <h1 class="h2-title">Terms of Service</h1>
  <h2>Storage of your Personal Data</h2>
  <p>We will only retain your Personal Data for as long as necessary to fulfill the purposes we collected it for, including for the purposes of satisfying any legal, accounting, or reporting requirements. If you assert a legitimate request for deletion or revoke consent for data processing, your data will be deleted unless we have other legally permissible reasons for storing your Personal Data (e.g. retention periods under tax or commercial law); in the latter case, deletion will take place after these reasons cease to apply. OCTO reserves the right to delete your account and all your data in case of inactivity for 3 years or more provided there are no tokens on your account balance.</p>
  <p>This Privacy Policy applies to BLACKBIRD SECURE BROWSING LTD (LTD registered Unit 1058, Second Floor, 6 Market Place, London, Fitzrovia, United Kingdom, W1W 8AF) and its affiliates, authorized resellers or distributors (“OCTO”, “we” or “us”). The security of your personal information is important to us. This Privacy Policy is designed to help you feel more confident about the privacy and security of your information when using or accessing any OCTO’s software, products, and services or any other digital content (“Software”). We do not share or sell information to any third party and we proactively protect all user data from disclosure, except when it’s necessary to provide OCTO’s services (like when we partner with payment processors) or as required by judicial or administrative order, applicable law, rule or regulation, or otherwise. This Privacy Policy (together with our Terms of Service) sets out the basis on which we process any personal information we collect from you, or that you provide to us through the Software. If you do not agree to the terms of this Privacy Policy, please do not provide us with any information and do not use the Software. Type and purpose of Data collected by OCTO Personal Data, or personal information, means any information about an individual from which that person can be identified. It does not include data where the identity has been removed (anonymous data). We may collect, use, store, and transfer different kinds of personal data about you which we have grouped together as follows:</p>
  <p>Contact information. When creating an Octo Browser account, we may ask for an email address. The email address will be used to identify you as a user, administer your account with us, send you communications we think you may find useful, but only in accordance with your email preferences, and for password recovery. You can also provide us with your login in the Telegram messenger for quick communication with support. You can delete or modify the submitted data using your profile page. Also, you can send us a request to delete your account. We will fulfill this request within 7 business days. Your personal data will be erased according to EU General Data Protection Regulation (GDPR) requirements. Financial and transaction Data includes bank account and payment card details, date of purchase, purchase amount, details about payments to and from you, team ID, and other details of products and services. We use this information for tracking purchases and usage information.
  Technical Data such as device operating system and hardware configuration, type of internet connection; memory, basic information about crashes and errors; time of page view, current date, and other similar information. The collection of this data takes place automatically as soon as you enter this website. When Octo Browser sends data to us, your IP address is temporarily collected as part of our server logs.
  Cookies. Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device’s internal memory. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. For more information, you may visit the website link or link.
  Please note, that we do not collect any Special Categories of Personal Data about you (this includes details about your race or ethnicity, religious or philosophical beliefs, sex life, sexual orientation, political opinions, trade union membership, information about your health, and genetic and biometric data). Nor do we collect any information about criminal convictions and offenses.</p>

  <h2>Storage of your Personal Data</h2>
  <p>We will only retain your Personal Data for as long as necessary to fulfill the purposes we collected it for, including for the purposes of satisfying any legal, accounting, or reporting requirements. If you assert a legitimate request for deletion or revoke consent for data processing, your data will be deleted unless we have other legally permissible reasons for storing your Personal Data (e.g. retention periods under tax or commercial law); in the latter case, deletion will take place after these reasons cease to apply. OCTO reserves the right to delete your account and all your data in case of inactivity for 3 years or more provided there are no tokens on your account balance.</p>

  <h2>Storage of your Personal Data</h2>
  <p>We will only retain your Personal Data for as long as necessary to fulfill the purposes we collected it for, including for the purposes of satisfying any legal, accounting, or reporting requirements. If you assert a legitimate request for deletion or revoke consent for data processing, your data will be deleted unless we have other legally permissible reasons for storing your Personal Data (e.g. retention periods under tax or commercial law); in the latter case, deletion will take place after these reasons cease to apply. OCTO reserves the right to delete your account and all your data in case of inactivity for 3 years or more provided there are no tokens on your account balance.
  s, and for password recovery. You can also provide us with your login in the Telegram messenger for quick communication with support. You can delete or modify the submitted data using your profile page. Also, you can send us a request to delete your account. We will fulfill this request within 7 business days. Your personal data will be erased according to EU General Data Protection Regulation (GDPR) requirements. Financial and transaction Data includes bank account and payment card details, date of purchase, purchase amount, details about payments to and from you, team ID, and other details of products and services. We use this information for tracking purchases and usage information.
  Technical Data such as device operating system and hardware configuration, type of internet connection; memory, basic information about crashes and errors; time of page view, current date, and other similar information. The collection of this data takes place automatically as soon as you enter this website. When Octo Browser sends data to us, your IP address is temporarily collected as part of our server logs.
  Cookies. Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device’s internal memory. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. For more information, you may visit the website link or link.
  Please note, that we do not collect any Special Categories of Personal Data about you (this includes details about your race or ethnicity, religious or philosophical beliefs, sex life, sexual orientation, political opinions, trade union membership, information about your health, and genetic and biometric data). Nor do we collect any information about criminal convictions and offen.</p>
</template>